ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "owners" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "issue_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "cert_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "issue_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "area" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "plot_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "hamlet" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "old_commune" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "new_commune" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "blocking_documents" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "unblock_doc" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "is_unblocked" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "cccd" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "ward" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "landPlot" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "mapSheet" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "group" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "recordType" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "receivedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "deadline" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "assignedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "submissionDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "approvalDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "completedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "privateNotes" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "personalNotes" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorizedBy" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authDocType" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "otherDocs" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "exportBatch" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "exportDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "measurementNumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "excerptNumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "reminderDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "lastRemindedAt" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "receiptNumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "resultReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "receiverName" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "needsMapCorrection" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "attached_files" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "old_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "new_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "old_area" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "old_plot_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "new_plot_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "issuenumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "entrynumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "issuedate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "residentialarea" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "customerAddress" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "issueNumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "entryNumber" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "issueDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "residentialArea" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "submittedTo" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "handoverWard" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "receivedBy" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "checkedBy" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "pendingCheckDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "checkedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "completedWorkDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "advancePayment" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "price" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "plotCount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "hasDefect" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "defectReason" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "defectDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "isDeptSynced" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "receiptType" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "paymentAmount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "rejectReason" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "rejectDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "explanationPlan" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "deadlineReminded" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "isHandedOver" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "statusLogs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "archiveHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "archiveHandoverBatch" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "capGiaySubStep" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "stepAssignments" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "thamDinhDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "phieuChuyenThueDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "inHoanThienDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "soPhieuChuyenThue" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "tax_transfer_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "tax_notice_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "tax_paid_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "printed_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorized_by" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorized_person_name" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorized_person_id" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorized_person_phone" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorized_person_address" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorizedPersonName" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorizedPersonId" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorizedPersonPhone" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "authorizedPersonAddress" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "needs_map_correction" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "explanation_plan" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "status_logs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "archive_handover_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "archive_handover_batch" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "procedure_id" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "original_appointment_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "actual_return_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "vat_amount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "total_fee" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "returnedBy" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "returnedPrice" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "group_name" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "payment_method" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "is_extended" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "extension_days" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "extension_reason" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "cancel_reason" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "batch_id" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "sourceType" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "return_receipt_number" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "return_recipient_name" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "return_recipient_phone" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "return_note" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "is_archived" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "archived_at" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "sourcetype" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "archive_code" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "requester_name" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "requester_phone" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "requester_id_card" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "content_request" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "surveyorId" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "fieldAssignedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "fieldCompletedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "drafterId" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "officeAssignedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "surveyor_id" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "field_assigned_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "field_completed_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "drafter_id" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "office_assigned_date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "surveyAssignedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "officeCompletedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "dossierComponents" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "attachedFiles" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "createdAt" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "updatedAt" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "postingDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "postingEndDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "appraisalDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "taxTransferDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "taxKv7Date" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "taxPaymentDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "printCertDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "pendingHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "sourceTable" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "previousStatus" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementReason" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementRequestDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementReturnStatus" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementRequestedBy" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementRequestedAt" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementStartedAt" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementCompletedBy" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementCompletedAt" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "supplementConfirmedBy" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "pendingSupplementReason" TEXT;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "certificate_owners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "certificateOwners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.land_records ADD COLUMN IF NOT EXISTS "data" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "owners" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "issue_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "cert_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "issue_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "area" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "plot_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "hamlet" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "old_commune" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "new_commune" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "blocking_documents" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "unblock_doc" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "is_unblocked" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "cccd" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "ward" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "landPlot" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "mapSheet" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "group" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "recordType" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "receivedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "deadline" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "assignedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "submissionDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "approvalDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "completedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "privateNotes" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "personalNotes" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorizedBy" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authDocType" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "otherDocs" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "exportBatch" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "exportDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "measurementNumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "excerptNumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "reminderDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "lastRemindedAt" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "receiptNumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "resultReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "receiverName" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "needsMapCorrection" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "attached_files" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "old_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "new_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "old_area" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "old_plot_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "new_plot_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "issuenumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "entrynumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "issuedate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "residentialarea" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "customerAddress" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "issueNumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "entryNumber" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "issueDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "residentialArea" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "submittedTo" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "handoverWard" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "receivedBy" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "checkedBy" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "pendingCheckDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "checkedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "completedWorkDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "advancePayment" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "price" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "plotCount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "hasDefect" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "defectReason" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "defectDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "isDeptSynced" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "receiptType" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "paymentAmount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "rejectReason" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "rejectDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "explanationPlan" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "deadlineReminded" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "isHandedOver" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "statusLogs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "archiveHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "archiveHandoverBatch" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "capGiaySubStep" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "stepAssignments" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "thamDinhDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "phieuChuyenThueDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "inHoanThienDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "soPhieuChuyenThue" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "tax_transfer_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "tax_notice_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "tax_paid_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "printed_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorized_by" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorized_person_name" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorized_person_id" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorized_person_phone" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorized_person_address" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorizedPersonName" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorizedPersonId" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorizedPersonPhone" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "authorizedPersonAddress" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "needs_map_correction" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "explanation_plan" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "status_logs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "archive_handover_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "archive_handover_batch" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "procedure_id" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "original_appointment_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "actual_return_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "vat_amount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "total_fee" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "returnedBy" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "returnedPrice" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "group_name" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "payment_method" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "is_extended" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "extension_days" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "extension_reason" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "cancel_reason" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "batch_id" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "sourceType" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "return_receipt_number" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "return_recipient_name" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "return_recipient_phone" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "return_note" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "is_archived" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "archived_at" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "sourcetype" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "archive_code" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "requester_name" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "requester_phone" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "requester_id_card" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "content_request" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "surveyorId" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "fieldAssignedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "fieldCompletedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "drafterId" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "officeAssignedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "surveyor_id" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "field_assigned_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "field_completed_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "drafter_id" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "office_assigned_date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "surveyAssignedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "officeCompletedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "dossierComponents" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "attachedFiles" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "createdAt" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "updatedAt" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "postingDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "postingEndDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "appraisalDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "taxTransferDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "taxKv7Date" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "taxPaymentDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "printCertDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "pendingHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "sourceTable" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "previousStatus" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementReason" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementRequestDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementReturnStatus" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementRequestedBy" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementRequestedAt" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementStartedAt" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementCompletedBy" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementCompletedAt" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "supplementConfirmedBy" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "pendingSupplementReason" TEXT;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "certificate_owners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "certificateOwners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.records ADD COLUMN IF NOT EXISTS "data" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "owners" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "issue_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "cert_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "issue_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "area" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "plot_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "hamlet" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "old_commune" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "new_commune" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "blocking_documents" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "unblock_doc" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "is_unblocked" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "cccd" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "ward" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "landPlot" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "mapSheet" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "group" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "recordType" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "receivedDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "deadline" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "assignedDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "submissionDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "approvalDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "completedDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "privateNotes" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "personalNotes" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorizedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authDocType" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "otherDocs" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "exportBatch" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "exportDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "measurementNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "excerptNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "reminderDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "lastRemindedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "receiptNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "resultReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "receiverName" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "needsMapCorrection" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "attached_files" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "old_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "new_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "old_area" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "old_plot_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "new_plot_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "issuenumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "entrynumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "issuedate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "residentialarea" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "customerAddress" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "issueNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "entryNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "issueDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "residentialArea" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "submittedTo" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "handoverWard" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "receivedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "checkedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "pendingCheckDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "checkedDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "completedWorkDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "advancePayment" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "price" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "plotCount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "hasDefect" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "defectReason" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "defectDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "isDeptSynced" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "receiptType" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "paymentAmount" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "rejectReason" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "rejectDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "explanationPlan" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "deadlineReminded" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "isHandedOver" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "statusLogs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "archiveHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "archiveHandoverBatch" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "capGiaySubStep" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "stepAssignments" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "thamDinhDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "phieuChuyenThueDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "inHoanThienDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "soPhieuChuyenThue" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_transfer_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_notice_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_paid_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printed_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "transferees" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_form_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorized_person_name" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorized_person_id" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorized_person_phone" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorized_person_address" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorizedPersonName" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorizedPersonId" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorizedPersonPhone" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "authorizedPersonAddress" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_form_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_form_staff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_kv7_transfer_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_kv7_staff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_notice_staff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "print_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "print_staff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "explanation_plan" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "returned_price" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_payment_receipt_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "receipt_type" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "receiver_name" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "personal_notes" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "private_notes" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "reminder_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "other_docs" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "received_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "deadline_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "completed_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "tax_returned_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "customer_notified_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "signed_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "cancelled_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "cancel_reason" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "current_step_code" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "current_step_name" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "progress_status" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "processing_steps" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxFormNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxFormStaff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxKV7TransferDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxKV7Staff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxNoticeDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxNoticeStaff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxPaymentReceiptDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printStaff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "invoiceNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "feeAmount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "returnedPrice" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "returnedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "group_name" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "procedure_id" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "original_appointment_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "actual_return_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "vat_amount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "total_fee" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "payment_method" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "is_extended" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "extension_days" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "extension_reason" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "batch_id" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "sourceType" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "return_receipt_number" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "return_recipient_name" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "return_recipient_phone" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "return_note" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "is_archived" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "archived_at" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "createdAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "updatedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "totalArea" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "appraisalDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "appraisalStaff" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxFormDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "applicantName" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "applicantPhone" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "applicantCccd" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "applicantAddress" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "applicantIsOwner" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "submitterName" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "submitterPhone" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "nonBoundaryWard" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "isNonBoundary" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "deliveryDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "attachedDocs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "attachedDocuments" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "dossierComponents" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "attachedFiles" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "returnBatch" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "returnBatchDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "returnHandoverDept" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "postingDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "postingEndDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxTransferDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxKv7Date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "taxPaymentDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printCertDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "pendingHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "sourceTable" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "previousStatus" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementReason" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementRequestDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementReturnStatus" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementRequestedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementRequestedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementStartedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementCompletedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementCompletedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "supplementConfirmedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "pendingSupplementReason" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printStaffId" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "print_staff_id" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printStaffAssignedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "print_staff_assigned_at" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printAssignmentStatus" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "print_assignment_status" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "printDeadlineStartAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "print_deadline_start_at" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "paymentReceivedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "payment_received_at" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "paymentReceiptDate" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "payment_receipt_date" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "certificateNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "bookNumber" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "data" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "assignedAt" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "assignedBy" TEXT;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "certificateOwners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.dangky_records ADD COLUMN IF NOT EXISTS "certificate_owners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "owners" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "issue_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "cert_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "issue_date" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "area" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "plot_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "hamlet" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "old_commune" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "new_commune" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "blocking_documents" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "unblock_doc" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "is_unblocked" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "cccd" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "ward" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "landPlot" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "mapSheet" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "group" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "recordType" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "receivedDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "deadline" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "assignedDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "submissionDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "approvalDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "completedDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "privateNotes" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "personalNotes" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorizedBy" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authDocType" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "otherDocs" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "exportBatch" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "exportDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "measurementNumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "excerptNumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "reminderDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "lastRemindedAt" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "receiptNumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "resultReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "receiverName" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "needsMapCorrection" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "attached_files" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "old_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "new_map_sheet_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "old_area" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "old_plot_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "new_plot_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "issuenumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "entrynumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "issuedate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "residentialarea" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "customerAddress" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "issueNumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "entryNumber" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "issueDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "residentialArea" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "submittedTo" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "handoverWard" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "receivedBy" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "checkedBy" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "pendingCheckDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "checkedDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "completedWorkDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "advancePayment" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "price" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "plotCount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "hasDefect" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "defectReason" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "defectDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "isDeptSynced" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "receiptType" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "paymentAmount" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "rejectReason" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "rejectDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "explanationPlan" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "deadlineReminded" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "isHandedOver" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "statusLogs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "archiveHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "archiveHandoverBatch" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "capGiaySubStep" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "stepAssignments" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "thamDinhDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "phieuChuyenThueDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "inHoanThienDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "soPhieuChuyenThue" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "so_hieu" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "trich_yeu" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "ngay_thang" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "noi_nhan_gui" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "data" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "status_logs" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "archive_handover_date" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "archive_handover_batch" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorized_person_name" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorized_person_id" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorized_person_phone" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorized_person_address" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "returnedBy" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "returnedPrice" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "group_name" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "procedure_id" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "original_appointment_date" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "actual_return_date" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "vat_amount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "total_fee" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "payment_method" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "is_extended" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "extension_days" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "extension_reason" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "cancel_reason" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "batch_id" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "sourceType" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "return_receipt_number" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "return_recipient_name" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "return_recipient_phone" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "return_note" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "is_archived" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "archived_at" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorizedPersonAddress" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorizedPersonName" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorizedPersonId" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorizedPersonPhone" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "sourcetype" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "authorized_by" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "dossierComponents" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "attachedFiles" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "type" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "createdAt" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "updatedAt" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "appraisalDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "postingDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "postingEndDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "taxTransferDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "taxKv7Date" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "taxPaymentDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "printCertDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "pendingHandoverDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "sourceTable" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "previousStatus" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementReturnStatus" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementReason" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementRequestedBy" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementRequestedAt" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementStartedAt" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementCompletedBy" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementCompletedAt" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementConfirmedBy" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementRequestDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "supplementReturnedDate" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "pendingSupplementReason" TEXT;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "certificate_owners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.luutru_records ADD COLUMN IF NOT EXISTS "certificateOwners" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "customerName" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "customerAddress" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "ward" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "landPlot" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "mapSheet" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "area" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "contractType" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "serviceType" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "areaType" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "plotCount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "markerCount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "splitItems" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "quantity" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "unitPrice" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "vatRate" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "vatAmount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "totalAmount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "deposit" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "createdDate" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "liquidationArea" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "liquidationAmount" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "cccd" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "recordType" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "liquidationDate" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "createdAt" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "updatedAt" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "surveyorId" TEXT;
ALTER TABLE IF EXISTS public.contracts ADD COLUMN IF NOT EXISTS "drafterId" TEXT;
ALTER TABLE IF EXISTS public.thongtin_records ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.thongtin_records ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.thongtin_records ADD COLUMN IF NOT EXISTS "customer_name" TEXT;
ALTER TABLE IF EXISTS public.thongtin_records ADD COLUMN IF NOT EXISTS "data" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.vphc_records ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.vphc_records ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.vphc_records ADD COLUMN IF NOT EXISTS "customer_name" TEXT;
ALTER TABLE IF EXISTS public.vphc_records ADD COLUMN IF NOT EXISTS "record_type" TEXT;
ALTER TABLE IF EXISTS public.vphc_records ADD COLUMN IF NOT EXISTS "data" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.chinhly_records ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.chinhly_records ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.chinhly_records ADD COLUMN IF NOT EXISTS "customer_name" TEXT;
ALTER TABLE IF EXISTS public.chinhly_records ADD COLUMN IF NOT EXISTS "data" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.work_schedules ADD COLUMN IF NOT EXISTS "date" TEXT;
ALTER TABLE IF EXISTS public.work_schedules ADD COLUMN IF NOT EXISTS "executors" TEXT;
ALTER TABLE IF EXISTS public.work_schedules ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE IF EXISTS public.work_schedules ADD COLUMN IF NOT EXISTS "partner" TEXT;
ALTER TABLE IF EXISTS public.work_schedules ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.work_schedules ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "position" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "managedWards" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "active" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "createdAt" TEXT;
ALTER TABLE IF EXISTS public.employees ADD COLUMN IF NOT EXISTS "updatedAt" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "username" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "role" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "employeeId" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "active" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "permissions" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "customPermissions" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "avatar" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "createdAt" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "updatedAt" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "position" TEXT;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS "managedWards" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "batch_name" TEXT;
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "batch_number" TEXT;
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "module_type" TEXT;
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "record_ids" JSONB DEFAULT '{}'::jsonb;
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "record_count" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.archive_batches ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "serviceGroup" TEXT;
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "areaType" TEXT;
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "serviceName" TEXT;
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "minArea" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "maxArea" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "unit" TEXT;
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "price" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "vatRate" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "vatIsPercent" BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS public.price_list ADD COLUMN IF NOT EXISTS "created_at" TEXT;
ALTER TABLE IF EXISTS public.system_settings ADD COLUMN IF NOT EXISTS "key" TEXT;
ALTER TABLE IF EXISTS public.system_settings ADD COLUMN IF NOT EXISTS "value" TEXT;
ALTER TABLE IF EXISTS public.system_settings ADD COLUMN IF NOT EXISTS "updated_at" TEXT;
ALTER TABLE IF EXISTS public.excerpt_counters ADD COLUMN IF NOT EXISTS "ward" TEXT;
ALTER TABLE IF EXISTS public.excerpt_counters ADD COLUMN IF NOT EXISTS "count" DECIMAL(15, 2);
ALTER TABLE IF EXISTS public.trichdo_counters ADD COLUMN IF NOT EXISTS "ward" TEXT;
ALTER TABLE IF EXISTS public.trichdo_counters ADD COLUMN IF NOT EXISTS "count" DECIMAL(15, 2);